### ISSUE TITLE
Find a set of fonts

### ISSUE THREAD

**Issue by benjaminsampica** [morkusporkus/DMPowerTools#34]
Need a font for headers, links, bolds, etc. - headliner type of things
Need a separate font for text.

**Comment by AndrewD713** [comment]
Regarding the proposal, my vote would be Cormorant for headliners and Crimson for text.

The others are neat, but can be a little difficult to read imo.

**Comment by benjaminsampica** [comment]
Votes are in

- Cormorant for headliners
- Crimson for text.
